[versions]
androidGradlePlugin = "8.4.0-alpha09"

kotlin = "1.9.22"
kotlinCoroutines = "1.8.0-RC2"
kotlinx-datetime = "0.5.0"

androidBuildTools = "34"
androidSdk = "34"
androidSdkMinimum = "26"

dokkaPlugin = "1.9.10"
junit = "4.13.2"
androidxTest = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTestExt = "1.1.5"

[libraries]
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

#build only
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest"}
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-test-ext = { module = "androidx.test.ext:junit", version.ref="androidxTestExt" }

[bundles]
androidx-test = [ "androidx-test-core", "androidx-test-runner", "androidx-test-ext"]

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-atomicfu = { id = "org.jetbrains.kotlin.plugin.atomicfu", version.ref = "kotlin" }

dokka = { id = "org.jetbrains.dokka", version.ref = "dokkaPlugin" }